import { chromium } from 'playwright-core'
import assert from 'node:assert/strict'
const browser=await chromium.launch({channel:'chrome',headless:true})
try {
 const page=await browser.newPage({viewport:{width:1280,height:900}})
 const errors=[]; page.on('pageerror',e=>errors.push(e.message))
 await page.goto('http://localhost:5173/slime-check/')
 const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('spielzeuge.slime-check.v1')))
 await page.screenshot({path:'tmp/slime-desktop.png',fullPage:true})
 await page.click('[data-action="pet"]'); assert.equal((await read()).coins,20)
 await page.click('[data-room="closet"]'); await page.click('[data-buy="berry"]'); assert.equal((await read()).coins,0)
 await page.click('[data-action="hold"]'); await page.click('[data-room="outside"]')
 const box=await page.locator('#slime').boundingBox(); const scene=await page.locator('#scene').boundingBox()
 await page.mouse.move(box.x+box.width/2,box.y+box.height/2); await page.mouse.down(); await page.mouse.move(scene.x+scene.width*.7,scene.y+scene.height*.9,{steps:15}); await page.mouse.up()
 assert.equal((await read()).clean,30)
 await page.click('nav [data-room="bath"]'); await page.click('[data-action="wash"]'); assert.equal((await read()).clean,55)
 await page.click('nav [data-room="bed"]'); await page.click('[data-action="sleep"]'); await page.waitForTimeout(4200); assert.equal((await read()).energy,100)
 await page.click('nav [data-room="stretch"]')
 const jelly=await page.locator('#slime').boundingBox(); await page.mouse.move(jelly.x+jelly.width/2,jelly.y+jelly.height/2); await page.mouse.down(); await page.mouse.move(jelly.x+jelly.width/2+145,jelly.y+jelly.height/2,{steps:12}); await page.mouse.up()
 assert.ok((await read()).record>200)
 const saved=await read(); await page.reload(); assert.deepEqual(await read(),saved)
 await page.setViewportSize({width:390,height:844}); await page.screenshot({path:'tmp/slime-phone.png',fullPage:true})
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)
 await page.click('nav [data-room="closet"]'); await page.screenshot({path:'tmp/slime-shop-phone.png',fullPage:true})
 assert.equal(await page.locator('[data-buy="berry"]').getAttribute('aria-pressed'),'true')
 await page.goto('http://localhost:5173/'); await page.click('a[href="./slime-check/"]'); assert.ok(page.url().includes('/slime-check/'))
 assert.deepEqual(errors,[])
 console.log('PASS: care → purchase → carry → outdoor drop → wash → sleep → drag record → reload; phone layout; catalog; no JS errors')
} finally {await browser.close()}
