import type { Lang } from './languages.ts'
const ru = {
  pairs: ['3 пары', '6 пар'],
  name: 'Собачка',
  tagline: 'Маленький друг. Большой мир.',
  home: 'Все игрушки',
  room: 'Мой уютный дом',
  kitchen: 'На кухне',
  garden: 'На прогулке',
  games: 'Наши игры',
  feed: 'Покормить',
  walk: 'Погулять',
  sleep: 'Спать',
  ball: 'Мячик',
  wall: 'Обои',
  pet: 'Погладить собачку',
  toy: 'Поиграть с пищалкой',
  back: 'Домой',
  welcome: 'Привет! Давай дружить?',
  hint: 'Погладь собачку или выбери, чем заняться.',
  friendship: 'Наша дружба',
  heartHint: 'Забота открывает новые игры',
  gameNames: ['Поймай мяч', 'Найди пару', 'Подбери фигуру'],
  gameHints: [
    'Бросай, а я принесу!',
    'У каждой картинки есть друг.',
    'Найди такую же фигурку.',
  ],
  open: 'Играть',
  locked: 'Сердечки заботы',
  allOpen: 'Все игры открыты. Как здорово быть друзьями!',
  gamesHint: 'Заботься обо мне — будем играть в новые игры!',
  foodHint: 'Перетащи еду к миске или просто нажми на неё.',
  foodNames: ['Корм', 'Морковка', 'Яблочко'],
  bowl: 'Миска собачки',
  eating: 'Ам-ням! Как вкусно!',
  fed: 'Спасибо за угощение! ♥',
  sleepHint: 'Тс-с… маленький сон.',
  slept: 'Выспалась! Можно снова играть. ♥',
  wake: 'Разбудить',
  ballHint: 'Ура, мячик! Туда-сюда!',
  played: 'Как весело играть вместе! ♥',
  walkHint: 'Нажимай на цветочки — соберём букет!',
  walked: 'Вот это прогулка! Букет для тебя. ♥',
  petHappy: 'Я тебя тоже люблю!',
  squeak: 'Пи-пи! Моя любимая игрушка!',
  walls: ['Весёлые фигурки', 'Цветочный сад', 'Сонные звёздочки'],
  fetchHint: 'Нажми на мячик — я побегу за ним!',
  memoryHint: 'Открой две карточки. Найди все пары!',
  shapeHint: 'Нажми на такую же фигуру внизу.',
  againHint: 'Попробуй ещё. У тебя получится!',
  match: 'Вот они, друзья!',
  win: 'У нас получилось!',
  winHint: 'Ещё одна маленькая радость вместе.',
  again: 'Ещё раз',
  help: 'Послушать подсказку',
  soundOn: 'Звук включён',
  soundOff: 'Звук выключен',
  language: 'Язык',
  saved: 'Твой друг будет ждать здесь.',
  notSaved: 'В этом браузере прогресс сохранится только до закрытия игры.',
  shapes: ['Круг', 'Треугольник', 'Квадрат', 'Звезда'],
  flower: 'Собрать цветочек',
  card: 'Карточка',
}
type Copy = {
  [K in keyof typeof ru]: (typeof ru)[K] extends string[] ? string[] : string
}
export const PUPPY_COPY: Record<Lang, Copy> = {
  ru,
  en: {
    pairs: ['3 pairs', '6 pairs'],
    name: 'Little Puppy',
    tagline: 'A little friend. A big world.',
    home: 'All toys',
    room: 'My cozy home',
    kitchen: 'In the kitchen',
    garden: 'Out for a walk',
    games: 'Our games',
    feed: 'Feed',
    walk: 'Walk',
    sleep: 'Sleep',
    ball: 'Ball',
    wall: 'Wallpaper',
    pet: 'Pet the puppy',
    toy: 'Play with the squeaky toy',
    back: 'Go home',
    welcome: 'Hello! Let’s be friends?',
    hint: 'Pet the puppy or pick something to do.',
    friendship: 'Our friendship',
    heartHint: 'Care unlocks new games',
    gameNames: ['Fetch the ball', 'Find a pair', 'Match the shape'],
    gameHints: [
      'Throw it, I’ll fetch!',
      'Every picture has a friend.',
      'Find the same little shape.',
    ],
    open: 'Play',
    locked: 'Care hearts',
    allOpen: 'All games are open. It’s lovely to be friends!',
    gamesHint: 'Care for me to discover new games together!',
    foodHint: 'Drag food to the bowl, or just tap it.',
    foodNames: ['Dog food', 'Carrot', 'Apple'],
    bowl: 'Puppy’s bowl',
    eating: 'Yum yum! Delicious!',
    fed: 'Thank you for the treat! ♥',
    sleepHint: 'Shh… a little nap.',
    slept: 'All rested! Let’s play again. ♥',
    wake: 'Wake up',
    ballHint: 'Yay, a ball! Back and forth!',
    played: 'Playing together is such fun! ♥',
    walkHint: 'Tap the flowers to pick a bouquet!',
    walked: 'What a lovely walk! Flowers for you. ♥',
    petHappy: 'I love you too!',
    squeak: 'Squeak! My favourite toy!',
    walls: ['Happy shapes', 'Flower garden', 'Sleepy stars'],
    fetchHint: 'Tap the ball and I’ll fetch it!',
    memoryHint: 'Turn over two cards. Find all the pairs!',
    shapeHint: 'Tap the matching shape below.',
    againHint: 'Try again. You can do it!',
    match: 'There they are, friends!',
    win: 'We did it!',
    winHint: 'Another little happy moment together.',
    again: 'Play again',
    help: 'Listen to a hint',
    soundOn: 'Sound on',
    soundOff: 'Sound off',
    language: 'Language',
    saved: 'Your friend will be waiting here.',
    notSaved: 'This browser can only keep progress until you close the game.',
    shapes: ['Circle', 'Triangle', 'Square', 'Star'],
    flower: 'Pick a flower',
    card: 'Card',
  },
  de: {
    pairs: ['3 Paare', '6 Paare'],
    name: 'Hündchen',
    tagline: 'Kleiner Freund. Große Welt.',
    home: 'Alle Spiele',
    room: 'Mein gemütliches Zuhause',
    kitchen: 'In der Küche',
    garden: 'Beim Spaziergang',
    games: 'Unsere Spiele',
    feed: 'Füttern',
    walk: 'Gassi',
    sleep: 'Schlafen',
    ball: 'Ball',
    wall: 'Tapete',
    pet: 'Hündchen streicheln',
    toy: 'Mit dem Quietschetier spielen',
    back: 'Nach Hause',
    welcome: 'Hallo! Wollen wir Freunde sein?',
    hint: 'Streichle das Hündchen oder suche etwas aus.',
    friendship: 'Unsere Freundschaft',
    heartHint: 'Fürsorge öffnet neue Spiele',
    gameNames: ['Hol den Ball', 'Finde ein Paar', 'Finde die Form'],
    gameHints: [
      'Wirf ihn, ich hole ihn!',
      'Jedes Bild hat einen Freund.',
      'Finde die gleiche kleine Form.',
    ],
    open: 'Spielen',
    locked: 'Fürsorgeherzen',
    allOpen: 'Alle Spiele sind offen. Freunde sein ist schön!',
    gamesHint: 'Kümmere dich um mich und entdecke neue Spiele!',
    foodHint: 'Ziehe Futter zum Napf oder tippe es an.',
    foodNames: ['Hundefutter', 'Karotte', 'Apfel'],
    bowl: 'Napf des Hündchens',
    eating: 'Mjam! Lecker!',
    fed: 'Danke für das Leckerli! ♥',
    sleepHint: 'Pst… ein kleines Nickerchen.',
    slept: 'Ausgeschlafen! Lass uns spielen. ♥',
    wake: 'Aufwecken',
    ballHint: 'Juhu, ein Ball! Hin und her!',
    played: 'Zusammen spielen macht Spaß! ♥',
    walkHint: 'Tippe auf die Blumen für einen Blumenstrauß!',
    walked: 'Ein schöner Spaziergang! Blumen für dich. ♥',
    petHappy: 'Ich hab dich auch lieb!',
    squeak: 'Quietsch! Mein Lieblingsspielzeug!',
    walls: ['Fröhliche Formen', 'Blumengarten', 'Schläfrige Sterne'],
    fetchHint: 'Tippe auf den Ball, ich hole ihn!',
    memoryHint: 'Decke zwei Karten auf. Finde alle Paare!',
    shapeHint: 'Tippe unten auf die gleiche Form.',
    againHint: 'Versuch es noch einmal. Du schaffst das!',
    match: 'Da sind die Freunde!',
    win: 'Wir haben es geschafft!',
    winHint: 'Noch ein kleiner Glücksmoment zusammen.',
    again: 'Noch einmal',
    help: 'Hinweis anhören',
    soundOn: 'Ton an',
    soundOff: 'Ton aus',
    language: 'Sprache',
    saved: 'Dein Freund wartet hier auf dich.',
    notSaved:
      'Dieser Browser speichert den Fortschritt nur bis zum Schließen des Spiels.',
    shapes: ['Kreis', 'Dreieck', 'Quadrat', 'Stern'],
    flower: 'Blume pflücken',
    card: 'Karte',
  },
}
